#import "./PromotorFragment.gql"

mutation createPromotor(
    $facebookId: String!, 
    $email: String!, 
  ) {
  createPromotor(
    facebookId: $facebookId, 
    email: $email
  ) {
    ...Promotor
  }
}